generic-service:
  nameOverride: hmpps-arns-assessment-platform-ui
  serviceAccountName: hmpps-arns-assessment-platform-service-account
  productId: 'HMPPS509' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources

  image:
    repository: ghcr.io/ministryofjustice/hmpps-arns-assessment-platform-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-arns-assessment-platform-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'hmpps-arns-assessment-platform-ui'
    GOTENBERG_API_URL: 'http://hmpps-arns-assessment-platform-ui-gotenberg'
    OASYS_URL: 'https://oasys.service.justice.gov.uk'
    MPOP_URL: 'https://manage-people-on-probation.hmpps.service.justice.gov.uk'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    hmpps-arns-assessment-platform-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-arns-assessment-platform-ui-auth-code:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'
    hmpps-arns-assessment-platform-ui-arns-handover:
      HMPPS_ARNS_HANDOVER_CLIENT_ID: 'HMPPS_ARNS_HANDOVER_CLIENT_ID'
      HMPPS_ARNS_HANDOVER_CLIENT_SECRET: 'HMPPS_ARNS_HANDOVER_CLIENT_SECRET'
    hmpps-arns-assessment-platform-ui-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    hmpps-arns-assessment-platform-ui-elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    hmpps-arns-assessment-platform-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'
      AUDIT_SQS_QUEUE_NAME: 'sqs_queue_name'
    assessment-query-cache-elasticache-redis:
      CACHE_REDIS_HOST: 'primary_endpoint_address'
      CACHE_REDIS_AUTH_TOKEN: 'auth_token'

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    scaleUpStabilizationWindowSeconds: 60

gotenberg:
  nameOverride: gotenberg
  replicaCount: 2

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  image:
    repository: gotenberg/gotenberg
    tag: 8.36.0
    port: 3000

  containerCommand: ['gotenberg']
  containerArgs:
    ['--chromium-clear-cookies', '--libreoffice-disable-routes', '--webhook-disable', '--prometheus-disable-collect']

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health
    periodSeconds: 30
    initialDelaySeconds: 60
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /health
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    privileged: false
    runAsNonRoot: true

generic-prometheus-alerts:
  targetApplication: hmpps-arns-assessment-platform-ui
